-- ============================================
-- THEME TABLE - Rang Palitra'lar
-- ============================================

-- Note: Jadval nomi "theam" (foydalanuvchi allaqachon yaratgan)
-- Agar "themes" ga o'zgartirmoqchi bo'lsangiz:
-- ALTER TABLE public.theam RENAME TO themes;

-- Agar jadval allaqachon mavjud bo'lmasa, yarating:
-- CREATE TABLE public.theam (
--   id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--   name TEXT NOT NULL,
--   colors TEXT
-- );

-- Mavjud jadvalga ustunlar qo'shamiz (agar yo'q bo'lsa)
ALTER TABLE public.theam 
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS is_default BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- colors ustunini TEXT dan JSONB ga o'zgartirish (agar kerak bo'lsa)
-- Agar colors ustuni allaqachon TEXT bo'lsa, uni JSONB ga o'zgartiring:
ALTER TABLE public.theam 
  ALTER COLUMN colors TYPE JSONB USING colors::jsonb;

-- Enable RLS
ALTER TABLE public.theam ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any
DROP POLICY IF EXISTS "Enable read for all users" ON public.theam;
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.theam;
DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.theam;
DROP POLICY IF EXISTS "Enable delete for authenticated users" ON public.theam;

-- Policies - Barchaga o'qishga ruxsat, faqat admin yozishi mumkin
CREATE POLICY "Enable read for all users" ON public.theam
  FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Enable insert for authenticated users" ON public.theam
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users" ON public.theam
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Enable delete for authenticated users" ON public.theam
  FOR DELETE TO authenticated USING (true);

-- Index
CREATE INDEX IF NOT EXISTS idx_theam_active ON public.theam(is_active);
CREATE INDEX IF NOT EXISTS idx_theam_default ON public.theam(is_default);

-- ============================================
-- DEFAULT THEMES - Tayyor Ranglar
-- ============================================

INSERT INTO public.theam (name, description, colors, is_default, is_active) VALUES
(
  'Ko''k-Binafsha-Yashil',
  'Default theme - professional va zamonaviy',
  '{"primary": "#2563EB", "secondary": "#9333EA", "accent": "#16A34A"}'::jsonb,
  true,
  true
),
(
  'Qizil-Pushti-Sariq',
  'Issiq va energiyali ranglar',
  '{"primary": "#DC2626", "secondary": "#EC4899", "accent": "#F59E0B"}'::jsonb,
  false,
  true
),
(
  'Moviy-Ko''k-Yashil',
  'Osmon va dengiz ranglari',
  '{"primary": "#0EA5E9", "secondary": "#3B82F6", "accent": "#10B981"}'::jsonb,
  false,
  true
),
(
  'Binafsha-Pushti-Qizil',
  'Romantik va nafis ranglar',
  '{"primary": "#7C3AED", "secondary": "#D946EF", "accent": "#F43F5E"}'::jsonb,
  false,
  true
),
(
  'Qora-Oltin',
  'Premium va hashamatli',
  '{"primary": "#1F2937", "secondary": "#F59E0B", "accent": "#FCD34D"}'::jsonb,
  false,
  true
),
(
  'Och Ko''k-Pushti',
  'Yumshoq va tinch ranglar',
  '{"primary": "#67E8F9", "secondary": "#F9A8D4", "accent": "#A78BFA"}'::jsonb,
  false,
  true
);

-- ============================================
-- Trigger for updated_at
-- ============================================
DROP TRIGGER IF EXISTS update_theam_updated_at ON public.theam;

CREATE TRIGGER update_theam_updated_at 
  BEFORE UPDATE ON public.theam
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- DONE! ✅
-- ============================================

